   name: Deploy Telegram Bot

   on:
     push:
       branches:
         - main  # Change this to your default branch if it's not 'main'

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.13.1'  # Specify the Python version you want to use

       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt

       - name: Run the bot
         env:
           TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Use GitHub Secrets for your token
         run: |
           python bot.py  # Replace with the name of your Python script
